ALTER TABLE formato13
  ADD COLUMN IF NOT EXISTS formato13_television ENUM('SI', 'NO') NOT NULL DEFAULT 'NO',
  ADD COLUMN IF NOT EXISTS formato13_video_45s ENUM('VIVENCIAL', 'INFORMATIVO', 'NO') NOT NULL DEFAULT 'NO',
  ADD COLUMN IF NOT EXISTS formato13_video_2_min ENUM('SI', 'NO') NOT NULL DEFAULT 'NO',
  ADD COLUMN IF NOT EXISTS formato13_video_2_min_explicacion TEXT NULL,
  ADD COLUMN IF NOT EXISTS formato13_video_url_red_social VARCHAR(2048) NULL;